accounts:
  - name: Reinhardt
    api_key: ****************************************************************
    api_secret: ****************************************************************
  - name: MonkeyWithAPlan
    api_key: ****************************************************************
    api_secret: ****************************************************************
  - name: VorTeXx
    api_key: ****************************************************************
    api_secret: ****************************************************************
  - name: Wow
    api_key: ****************************************************************
    api_secret: ****************************************************************
